---
title: "fillnodata!"
---

gdaltranslate(indata, options=String[]; dest="/vsimem/tmp", kwargs...)

Convert raster data between different formats.

Operations provided by the GDAL 'gdal_translate' tool. Namely sub-region extraction and resampling.
The `kwargs` options accept the GMT region (-R), increment (-I), target SRS (-J). Any of the keywords
`outgrid`, `outfile` or `save` = outputname options to make this function save the result on 
a file designated by 'outputname'. The file format is picked from the 'outputname' file extension.
When no output file name is provided it returns a GMT object (either a grid or an image, depending
on the input type). To force the return of a GDAL dataset use the option `gdataset=true`.

### Args
- `indata`: Input data. It can be a file name, a {{< gmtref GMTgrid type=gmttype >}} or {{< gmtref GMTimage type=gmttype >}} object or a GDAL dataset
- `options`: List of options. The accepted options are the ones of the gdal_translate utility.
            This list can be in the form of a vector of strings, or joined in a single string.

### Kwargs
- `meta=metadata`, where `metadata` is a string vector with the form "NAME=...." for each of
  its elements. This data will be recognized by GDAL as Metadata.
The `kwargs` may also contain the GMT region (-R), proj (-J), inc (-I) and `save=fname` options.
And it may also contain a `options=...` argument that is equivalent to the `options` positional argument,
  with the exception that the value may also be a Tuple.

### Returns
A GMT grid or Image, or a GDAL dataset (or nothing if file was writen on disk).
"""
function gdaltranslate(indata, opts=String[]; dest="/vsimem/tmp", kwargs...)
	helper_run_GDAL_fun(gdaltranslate, indata, dest, opts, "", kwargs...)
end
# ---------------------------------------------------------------------------------------------------

"""
    gdalwarp(indata, options=String[]; dest="/vsimem/tmp", kwargs...)

Image/Grid reprojection and warping function.

### Args
- `indata`:  Input data. It can be a file name, a {{< gmtref GMTgrid type=gmttype >}} or {{< gmtref GMTimage type=gmttype >}} object or a GDAL dataset
- `options`: List of options. The accepted options are the ones of the gdal_translate utility.
            This list can be in the form of a vector of strings, or joined in a single string.
            The accepted options are the ones of the gdalwarp utility.

- `kwargs`: Besides what was mentioned above one can also use `meta=metadata`, where `metadata`
            is a string vector with the form "NAME=...." for each of its elements. This data
            will be recognized by GDAL as Metadata.
            The `kwargs` may also contain the GMT region (-R), proj (-J), inc (-I) and `save=fname` options.

### Returns
A GMT grid or Image, or a GDAL dataset (or nothing if file was writen on disk).
"""
function gdalwarp(indata, opts=String[]; dest="/vsimem/tmp", kwargs...)
	helper_run_GDAL_fun(gdalwarp, indata, dest, opts, "", kwargs...)
end

# ---------------------------------------------------------------------------------------------------
