# arrows

```julia
arrows(cmd0::String="", arg1=nothing; arrow=(...), kwargs...)
```

Plot an arrow field.

When the keyword `arrow=(...)` or `vector=(...)` is used, the direction (in degrees counter-clockwise
from horizontal) and length must be found in columns 3 and 4, and size, if not specified on the command-line,
should be present in column 5. The size is the length of the vector head. Vector stem width is set by
option `pen` or `line_attrib`.

The `vecmap=(...)` variation is similar to above except azimuth (in degrees east of north) should be
given instead of direction. The azimuth will be mapped into an angle based on the chosen map projection.
If length is not in plot units but in arbitrary user units (e.g., a rate in mm/yr) then you can use the
*input_col* option to scale the corresponding column via the +sscale modifier.

The `geovec=(...)` or `geovector=(...)` keywords plot geovectors. In geovectors, azimuth (in degrees east
from north) and geographical length must be found in columns 3 and 4. The size is the length of the vector
head. Vector width is set by `pen` or `line_attrib`. Note: Geovector stems are drawn as thin filled polygons
and hence pen attributes like dashed and dotted are not available. For allowable geographical units, see
the `units=()` option.

The full `arrow` options list can be consulted at [Vector Attributes](../common_features/arrows_control.html)

{{< include ../common_opts/opt_B.md >}}

{{< include ../common_opts/opt_J.md >}}

{{< include ../common_opts/opt_R.md >}}

{{< include ../common_opts/opt_pen.md >}}

{{< include ../common_opts/opt_U.md >}}

{{< include ../common_opts/opt_V.md >}}

{{< include ../common_opts/opt_X.md >}}

{{< include ../common_opts/opt_Y.md >}}

{{< include ../common_opts/opt_save_fig.md >}}

Examples
--------

```{julia}
using GMT

arrows([0 8.2 0 6], limits=(-2,4,0,9), arrow=(len=2,stop=1,shape=0.5,fill=:red),
       axis=:a, pen="6p", show=true)
```
