# leepacific

```julia
GI[,coast] = leepacific(fname::String|GI::GItype; latlims=nothing, lonlims=nothing, coast=true)
```

Project a geographical grid/image in the Lee Oblated Stereographic projection centered on the Pacific Ocean.

- `GI`: A {{< gmtref GMTgrid type=gmttype >}} or {{< gmtref GMTimage type=gmttype >}} data type. `GI` can also be a string with a file name of a grid or image.
   NOTE: This grid/image should (ideally) have longitudes covering the range 76 to 319 degrees (here lon in [0 360] is better)

- `latlims`: Latitudes used in `region` when reading the grid/image. The default is (-87, 75).

- `lonlims`: Longitudes used in `region` when reading the grid/image. You cannot deviate mutch from (90,300).
   Actually, while a bug in GDAL is not fixed, you should not change the default values.

- `coast`: Return also the coastlines projected with `proj`. Pass `coast=res`, where `res` is one of
   GMT coastline resolutions (*e.g.* :crude, :low, :intermediate). `coast=true` is <==> `coast=:crude`
   Pass `coast=D`, where `D` is vector of {{< gmtref GMTdataset type=gmttype >}} containing coastline polygons with a provenience
   other than the GSHHG GMT database. If `coast=false` the funtion returns only the projected grid/image.

Note: This function uses {{< gmtref worldrectangular >}} with the `+proj=lee_os` projection. If one wants to add
other elements to the map (points, lines, etc) one must projectem first with the `+proj=lee_os` projection
(use [lonlat2xy] or {{< gmtref mapproject >}} to that purpose).

Returns
-------

A grid or a image and optionally the coastlines .

Example
-------


```{julia}
using GMT
G,cl = leepacific("@earth_relief_20m_g");
grdimage(G, shade=true, plot=(data=cl,), cmap=:geo, B=:none)
plotgrid!(G, show=true)
```


See Also
--------

{{< gmtref coastlinesproj >}}, {{< gmtref graticules >}}, [plotgrid!], {{< gmtref worldrectangular >}}, {{< gmtref worldrectgrid >}}, {{< gmtref worldrectcoast >}},
[Best rectangular world map projection]
```{julia}
#| echo: false
#| output: asis
using GMT
GMT.doc_source_links("leepacific")
```
