---
title: "pssolar"
---

# pssolar

```
solar(cmd0::String="", arg1=nothing; kwargs...)
```

Calculate and plot the day-night terminator and the civil, nautical and astronomical twilights.

See full GMT docs at [`solar`](http://docs.generic-mapping-tools.org/latest/solar.html)

## Parameters

  * **J** | **proj** | **projection** :: [Type => String]

    Select map projection. Defaults to 15x10 cm with linear (non-projected) maps.
  * **B** | **frame** | **axis** | **xaxis yaxis**:: [Type => Str] 

    Set map boundary frame and axes attributes.
  * **C** | **format** :: [Type => Bool]
  * **G** | **fill** :: [Type => Str | Number]
  * **I** | **sun** :: [Type => Bool | Tuple | NamedTuple]
  * **P** | **portrait** :: [Type => Bool or []]

    Tell GMT to **NOT** draw in portrait mode (that is, make a Landscape plot)
  * **M** | **dump** :: [Type => Bool]
  * **R** | **region** | **limits** :: [Type => Str or list or GMTgrid|image]	$Arg = (xmin,xmax,ymin,ymax)$

    Specify the region of interest. Set to data minimum BoundinBox if not provided.
  * **N** | **invert** :: [Type => Bool]
  * **T** | **terminators** :: [Type => Bool | Tuple | NamedTuple]
  * **W** | **pen** :: [Type => Str | Tuple]
  * **U** | **time_stamp** | **timestamp** :: [Type => Str or Bool or []]	$Arg = [[just]/dx/dy/][c|label]$

    Draw GMT time stamp logo on plot.
  * **V** | **verbose** :: [Type => Bool or Str]		$Arg = [level]$

    Select verbosity level, which will send progress reports to stderr.
  * **X** | **x_offset** | **xshift** :: [Type => Str]     $Arg = [a|c|f|r][x-shift[u]]$
  * **Y** | **y_offset** | **yshift** :: [Type => Str]     $Arg = [a|c|f|r][y-shift[u]]$

    Shift plot origin relative to the current origin by (x-shift,y-shift) and optionally   append the length unit (c, i, or p).
  * **bo** | **binary_out** :: [Type => Str]			$Arg = [ncols][type][w][+L|+B]$

    Select native binary output.
  * **h** | **header** :: [Type => Str]        $Arg = [i|o][n][+c][+d][+rremark][+ttitle]$

    Primary input file(s) has header record(s).
  * **o** | **outcols** | **outcol** :: [Type => Str]     $Arg = cols[,…]$

    Select specific data columns for primary output, in arbitrary order.
  * **p** | **view** | **perspective** :: [Type => Str or List]   $Arg = [x|y|z]azim[/elev[/zlevel]][+wlon0/lat0[/z0]][+vx0/y0]$

    Selects perspective view and sets the azimuth and elevation of the viewpoint [180/90].
  * **t** | **alpha** | **transparency** :: [Type => Str]   $Arg = transp$

    Set PDF transparency level for an overlay, in (0-100] percent range. [Default is 0, i.e., opaque].
  * **savefig** | **figname** | **name** :: [Type => Str]

    Save the figure with the `figname=name.ext` where `ext` chooses the figure format (e.g. figname="name.png")

To see the full documentation type: $@? solar$


## Methods

```julia
# 3 methods for generic function "solar" from GMT:
 [1] solar(cmd0::String; ...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\pssolar.jl:42
 [2] solar(; ...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\pssolar.jl:42
 [3] solar(cmd0::String, arg1; first, kwargs...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\pssolar.jl:42
```

## See Also

- [Alphabetical Function List](../alphabetical.html)
- [GMT.jl Documentation](https://www.generic-mapping-tools.org/GMTjl_doc/)
