---
title: "psxy"
---

# psxy

```
plot(arg1::Array; kwargs...)
```

reads (x,y) pairs from files [or standard input] and generates PostScript code that will plot lines, polygons, or symbols at those locations on a map.

See full GMT docs at [`psxy`](http://docs.generic-mapping-tools.org/latest/plot.html)

## Parameters

  * **A** | **steps** | **stairs** | **straight_lines** :: [Type => Str]

```
By default, geographic line segments are drawn as great circle arcs.
To draw them as straight lines, use this option.
```

  * **J** | **proj** | **projection** :: [Type => String]

    Select map projection. Defaults to 15x10 cm with linear (non-projected) maps.
  * **R** | **region** | **limits** :: [Type => Str or list or GMTgrid|image]	$Arg = (xmin,xmax,ymin,ymax)$

    Specify the region of interest. Set to data minimum BoundinBox if not provided.
  * **B** | **frame** | **axis** | **xaxis yaxis**:: [Type => Str] 

    Set map boundary frame and axes attributes.
  * **C** | **color** | **colormap** | **cmap** | **colorscale** :: [Type => Str]	$Arg = [cpt |master[+izinc] |color1,color2[,*color3*,…]]$

    Give a CPT name or specify -Ccolor1,color2[,color3,...] to build a linear continuous CPT from those   colors automatically.
  * **D** | **shift** | **offset** :: [Type => Str]

    Offset the plot symbol or line locations by the given amounts dx/dy in cm, inch or points.
  * **E** | **error** | **error_bars** :: [Type => Str]

    Draw symmetrical error bars.
  * **F** | **conn** | **connection** :: [Type => Str]

    Alter the way points are connected
  * **G** | **fill** | **markerfacecolor** | **MarkerFaceColor** | **markercolor** | **mc** :: [Type => Str]

    Select color or pattern for filling of symbols or polygons. BUT WARN: the alias 'fill' will set the   color of polygons OR symbols but not the two together. If your plot has polygons and symbols, use   'fill' for the polygons and 'markerfacecolor' for filling the symbols. Same applyies for W bellow
  * **I** | **intens** :: [Type => Str | number]

    Use the supplied intens value (in the [-1 1] range) to modulate the fill color by simulating illumination.
  * **L** | **close** | **polygon** :: [Type => Str]

    Force closed polygons.
  * **N** | **no_clip** | **noclip** :: [Type => Str or []]

    Do NOT clip symbols that fall outside map border
  * **P** | **portrait** :: [Type => Bool or []]

    Tell GMT to **NOT** draw in portrait mode (that is, make a Landscape plot)
  * **S** | **symbol** | **marker** | **Marker** :: [Type => Str]

    Plot symbols (including vectors, pie slices, fronts, decorated or quoted lines).    Alternatively select a sub-set of symbols using the aliases: **marker** or **Marker** and values:

      * **-**, **x_dash**
      * **+**, **plus**
      * **a**, *, **star**
      * **c**, **circle**
      * **d**, **diamond**
      * **g**, **octagon**
      * **h**, **hexagon**
      * **i**, **v**, **inverted_tri**
      * **n**, **pentagon**
      * **p**, **.**, **point**
      * **r**, **rectangle**
      * **s**, **square**
      * **t**, **^**, **triangle**
      * **x**, **cross**
      * **y**, **y_dash**

    and select their sizes with the **markersize** or **size** keyword [default is 7p].   The marker size can be a scalar or a vector with same size numeber of rows of data. Units are   points unless specified otherwise with (for example for cm) *par=(PROJ*LENGTH*UNIT="c")*
  * **W** | **pen** | **markeredgecolor** | **mec** :: [Type => Str]

    Set pen attributes for lines or the outline of symbols   WARNING: the pen attributes will set the pen of polygons OR symbols but not the two together.   If your plot has polygons and symbols, use **W** or **pen** for the polygons and   **markeredgecolor** for filling the symbols. Similar to S above.
  * **U** | **time_stamp** | **timestamp** :: [Type => Str or Bool or []]	$Arg = [[just]/dx/dy/][c|label]$

    Draw GMT time stamp logo on plot.
  * **V** | **verbose** :: [Type => Bool or Str]		$Arg = [level]$

    Select verbosity level, which will send progress reports to stderr.
  * **X** | **x_offset** | **xshift** :: [Type => Str]     $Arg = [a|c|f|r][x-shift[u]]$
  * **Y** | **y_offset** | **yshift** :: [Type => Str]     $Arg = [a|c|f|r][y-shift[u]]$

    Shift plot origin relative to the current origin by (x-shift,y-shift) and optionally   append the length unit (c, i, or p).
  * **Z** | **level** :: [Type => Str | NamedTuple]	`Arg = value|file[+f|+l] | (data=Array|Number, outline=_, fill=_)`

    Paint polygons after the level given as a cte or a vector with same size of number of polygons. Needs a color map.
  * **aspect** :: [Type => Str]

    When equal to "equal" makes a square plot.
  * **a** | **aspatial** :: [Type => Str]			$Arg = [col=]name[…]$

    Control how aspatial data are handled in GMT during input and output.
  * **bi** | **binary_in** :: [Type => Str]			$Arg = [ncols][type][w][+L|+B]$

    Select native binary format for primary input (secondary inputs are always ASCII).
  * **di** | **nodata_in** :: [Type => Str or Number]      $Arg = nodata$

    Examine all input columns and if any item equals nodata we interpret this value as a   missing data item and substitute the value NaN.
  * **e** | **pattern** | **find** :: [Type => Str]        $Arg = [~]”pattern” | -e[~]/regexp/[i]$

    Only accept ASCII data records that contains the specified pattern.
  * **f** | **geog** | **colinfo** | **coltypes** | **coltype** :: [Type => Str]        $Arg = [i|o]colinfo$

    Specify the data types of input and/or output columns (time or geographical data).
  * **g** | **gap** :: [Type => Str]           $Arg = [a]x|y|d|X|Y|D|[col]z[+|-]gap[u]$

    Examine the spacing between consecutive data points in order to impose breaks in the line.
  * **h** | **header** :: [Type => Str]        $Arg = [i|o][n][+c][+d][+rremark][+ttitle]$

    Primary input file(s) has header record(s).
  * **i** | **incols** | **incol** :: [Type => Str]      $Arg = cols[+l][+sscale][+ooffset][,…]$

    Select specific data columns for primary input, in arbitrary order.
  * **p** | **view** | **perspective** :: [Type => Str or List]   $Arg = [x|y|z]azim[/elev[/zlevel]][+wlon0/lat0[/z0]][+vx0/y0]$

    Selects perspective view and sets the azimuth and elevation of the viewpoint [180/90].
  * **t** | **alpha** | **transparency** :: [Type => Str]   $Arg = transp$

    Set PDF transparency level for an overlay, in (0-100] percent range. [Default is 0, i.e., opaque].
  * **w** | **wrap** | **cyclic** :: [Type => Str or Number]  $Arg = [[-]n]$

    Convert input records to a cyclical coordinate.
  * **yx** :: [Type => Str or Bool or []]     $Arg = [i|o]$

    Swap 1st and 2nd column on input and/or output.
  * **savefig** | **figname** | **name** :: [Type => Str]

    Save the figure with the `figname=name.ext` where `ext` chooses the figure format (e.g. figname="name.png")


## Methods

```julia
# 10 methods for generic function "plot" from GMT:
  [1] plot(cmd0::String; ...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\plot.jl:140
  [2] plot(cmd0::String, arg1; kw...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\plot.jl:140
  [3] plot(arg1::Number, arg2::Number; kw...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\plot.jl:144
  [4] plot(f::Function; ...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\plot.jl:129
  [5] plot(f1::Function, f2::Function; ...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\plot.jl:135
  [6] plot(f::Function, range_x; first, kw...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\plot.jl:129
  [7] plot(f1::Function, f2::Function, range_t; first, kw...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\plot.jl:135
  [8] plot(; ...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\plot.jl:140
  [9] plot(arg1, arg2; kw...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\plot.jl:142
 [10] plot(arg1; first, kw...)
     @ C:\Users\j\.julia\packages\GMT\Td19G\src\plot.jl:101
```

## See Also

- [Alphabetical Function List](../alphabetical.html)
- [GMT.jl Documentation](https://www.generic-mapping-tools.org/GMTjl_doc/)
