# imfill

```julia
I2 = imfill(I; conn=4, is_transposed=true, layout="TRBa")
```

Fill holes in the grayscale {{< gmtref GMTimage type=gmttype >}} I or UInt8 matrix I.

Here, a hole is defined as an area of dark pixels surrounded by lighter pixels.

### Args
- `I::Union{GMTimage{UInt8, 2}, GMTimage{Bool, 2}, Matrix{UInt8}, Matrix{Bool}, BitMatrix}`: Input image.

### Kwargs
- `conn::Int`: Connectivity for the image filling (4 or 8). Default is 4.

- `is_transposed::Bool`: If `true`, it informs that the input image array is transposed. Default is `true`.
   Normally the {{< gmtref GMTimage type=gmttype >}} carries information to know about the transposition (which is `true` when the layout is "TRB").
   When passing a matrix in column-major order (the default in Julia), `is_transposed` must be set to `false`.
   NOTE: The deaful is `true` because that is the normal case when reading a file image with {{< gmtref gmtread >}} or [gdalread].
  
- `layout::String`: Layout of the input Matrix (default is "TRBa"). If the input is a GMTimage,
   this argument should have been set automatically and can normally be ignored.

### Returns
- A new {{< gmtref GMTimage type=gmttype >}} (or Matrix) with the holes filled.

Examples
--------

Example from Matlab imfill.


```{julia}
using GMT

I = gdalread(TESTSDIR * "assets/coins.jpg");
Ibw1 = binarize(I);
Ibw2 = imfill(Ibw1);
grdimage(I, figsize=5)
grdimage!(Ibw1, figsize=5, xshift=5.1)
grdimage!(Ibw2, figsize=5, xshift=5.1, show=true)
```



See Also
--------

{{< gmtref fillsinks >}}, {{< gmtref binarize >}}
